# Generated by Django 2.2 on 2019-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_remove_route_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='users',
            field=models.ManyToManyField(to='riders.Profile'),
        ),
    ]
