# Generated by Django 2.2 on 2019-06-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_route_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='users',
            new_name='user',
        ),
    ]
