# Generated by Django 2.2 on 2019-06-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_auto_20190616_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='user',
            new_name='users',
        ),
    ]
